### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by HIT-Ygq** [chengwei0427/fast-lo#2]
![12](https://user-images.githubusercontent.com/90457565/221105709-24d3fb74-349c-4873-b485-fc633562b2c0.png)
![13](https://user-images.githubusercontent.com/90457565/221105718-e0f83ac4-b5dd-4c70-8fa7-4c7824b94415.png)
catkin_make之后没有任何信息

**Comment by chengwei0427** [comment]
Hi, @HIT-Ygq 

Thanks for your attention.

A **package.xml** is lost, I have uploaded it, and you can update the code.

**Comment by chengwei0427** [comment]
Hi， @HIT-Ygq 

Any feedback about the project?

**Comment by HIT-Ygq** [comment]
十分欣赏你的开源精神,缺少了rviz文件

**Comment by chengwei0427** [comment]
抱歉，已经上传了。

有什么想法或建议，欢迎交流。

**Comment by HIT-Ygq** [comment]
ok,向大佬学习
